# Generated by Django 5.1 on 2024-08-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['serial_number'], 'verbose_name': 'Департамент', 'verbose_name_plural': 'Департаменты'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['serial_number'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='employeestatus',
            options={'ordering': ['serial_number'], 'verbose_name': 'Статус сотрудника', 'verbose_name_plural': 'Статусы сотрудников'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['serial_number'], 'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
    ]
