# Generated by Django 5.1 on 2024-08-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_department_options_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='serial_number',
            field=models.PositiveIntegerField(blank=True, unique=True, verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='serial_number',
            field=models.PositiveIntegerField(blank=True, unique=True, verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='employeestatus',
            name='serial_number',
            field=models.PositiveIntegerField(blank=True, unique=True, verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='position',
            name='serial_number',
            field=models.PositiveIntegerField(blank=True, unique=True, verbose_name='Порядковый номер'),
        ),
    ]
