# Generated by Django 5.1 on 2024-08-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='serial_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Порядковый номер'),
        ),
    ]
