# Generated by Django 5.1 on 2024-08-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_employee_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='fired',
            field=models.BooleanField(default=False, verbose_name='Уволен'),
        ),
    ]
