# Generated by Django 5.1 on 2024-08-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_employee_fired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeestatus',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='employeestatus',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='employeestatus',
            name='color',
            field=models.CharField(default='#000000', max_length=7, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='employeestatus',
            name='serial_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Порядковый номер'),
        ),
    ]
