# Generated by Django 5.1 on 2024-08-28 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_remove_employeestatus_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ['serial_number']},
        ),
    ]
