# Generated by Django 5.1 on 2024-08-28 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_alter_division_department'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='division',
            unique_together=set(),
        ),
    ]
