# Generated by Django 5.1 on 2024-12-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_alter_employee_birth_date_alter_employee_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='short_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Название департамента'),
        ),
    ]
